// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nlrncxkqpijlivkpvqka.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5scm5jeGtxcGlqbGl2a3B2cWthIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0MjMxNzgsImV4cCI6MjA2NTk5OTE3OH0.jKONskS41uO0KwQL23t7969kC8PnJ9YX6wJdHO9SMWc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);